name: task1
description: Solution attempt for AoC 2021, day 1, task 1
version: 1.0.0

environment:
  sdk: '>=2.15.0-226.0.dev <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
